---
# See http://doc.silverstripe.org/framework/en/topics/configuration
# Caution: Indentation through two spaces, not tabs
Name: mysite
After: 'framework/*','cms/*','#boilerplate'
---
SSViewer:
  # display template filenames as comments in the html output
  source_file_comments: true
  # This boilerplace suggests using only the mysite folder without a theme
  # if you want to set a theme, change the 2 lines below
  theme_enabled: false
  # theme: 'simple'

MySQLDatabase:
  connection_charset: 'utf8'

GDBackend:
  default_quality: 100

SiteTree:
  nested_urls: true
  # Disable creating of default pages (like home) on /dev/build
  # create_default_pages: false

Email:
  admin_email: 'email@mysite.com'

SiteConfig:
  extensions:
    - SiteConfigExtension

LeftAndMain:
  extensions:
    - ProjectLeftAndMainExtension
  cms_menu_background: '#1b354c'
  cms_menu_active_text_color: '#fff'
  cms_menu_active_background_color: '#0d1a25'

ColorField:
  primary_color: '#3f51b5'
  secondary_color: '#ff4081'

PortfolioPage:
  extensions:
    - CatalogPageExtension
  parentClass:
    - 'PortfolioHolder'
  can_duplicate: false
  sort_column: false

BlogPage:
  extensions:
    - CatalogPageExtension
  parentClass:
    - 'BlogHolder'
  can_duplicate: false
  sort_column: false

SVGTemplate:
  base_path: mysite/images/svg
